### ISSUE TITLE
Drop Lineage FOD Policy

### ISSUE THREAD

**Issue by lasse-herzog** [crdroidandroid/android_device_xiaomi_cepheus#1]
Since LineageOS dropped the lineage FOD Policy: https://github.com/LineageOS/android_device_lineage_sepolicy/commit/d353083bca73b6499f6717fbf2f0cb78cb0bb1f5
the sepolicies in private/plattform_app.te and private/system_server.te need to be removed.

**Comment by raystef66** [comment]
@lasse-herzog  thx for pointing out - already pushed trees.
